### ISSUE TITLE
OpenTuner'S SQL Error

### ISSUE THREAD

**Issue by michael-hahn** [crimson-unicorn/modeling#1]
When running `model_ot.py`, I received the following error. However, if one runs this program again, the error disappears and it runs smoothly.
```default: cd build/modeling && GRAPHCHI_ROOT=../graphchi-cpp/ python model_ot.py --technique RegularStepSearch --test-limit 10 --base_folder_train ../../data/camflow-apt/train/base --stream_folder_train ../../data/camflow-apt/train/stream --base_folder_test ../../data/camflow-apt/test/base --stream_folder_test ../../data/camflow-apt/test/stream --sketch_folder_train ../../data/camflow-apt/train_sketch/ --sketch_folder_test ../../data/camflow-apt/test_sketch/ --sketch_size --k_hops --chunk_size --lambda_param > ot_interval.txt
    default: Traceback (most recent call last):
    default:   File "model_ot.py", line 333, in <module>
    default:     Unicorn.main(args)
    default:   File "/usr/lib/python2.7/site-packages/opentuner/measurement/interface.py", line 301, in main
    default:     return TuningRunMain(cls(args, *pargs, **kwargs), args).main()
    default:   File "/usr/lib/python2.7/site-packages/opentuner/tuningrunmain.py", line 201, in main
    default:     self.search_driver.main()
    default:   File "/usr/lib/python2.7/site-packages/opentuner/search/driver.py", line 272, in main
    default:     if self.run_generation_techniques() > 0:
    default:   File "/usr/lib/python2.7/site-packages/opentuner/search/driver.py", line 172, in run_generation_techniques
    default:     dr = self.root_technique.desired_result()
    default:   File "/usr/lib/python2.7/site-packages/opentuner/search/technique.py", line 93, in desired_result
    default:     cfg = self.desired_configuration()
    default:   File "/usr/lib/python2.7/site-packages/opentuner/search/technique.py", line 201, in desired_configuration
    default:     return next(self.gen)
    default:   File "/usr/lib/python2.7/site-packages/future/builtins/newnext.py", line 59, in newnext
    default:     return iterator.next()
    default:   File "/usr/lib/python2.7/site-packages/opentuner/search/technique.py", line 262, in call_main_generator
    default:     if not self.driver.has_results(p):
    default:   File "/usr/lib/python2.7/site-packages/opentuner/search/driver.py", line 158, in has_results
    default:     return self.results_query(config=config).count() > 0
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3561, in count
    default:     return self.from_self(col).scalar()
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3305, in scalar
    default:     ret = self.one()
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3275, in one
    default:     ret = self.one_or_none()
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3244, in one_or_none
    default:     ret = list(self)
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    default:     return self._execute_and_instances(context)
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    default:     result = conn.execute(querycontext.statement, self._params)
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    default:     return meth(self, multiparams, params)
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    default:     return connection._execute_clauseelement(self, multiparams, params)
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    default:     distilled_params,
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    default:     e, util.text_type(statement), parameters, None, None
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    default:     util.raise_from_cause(sqlalchemy_exception, exc_info)
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    default:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1179, in _execute_context
    default:     context = constructor(dialect, self, conn, *args)
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 683, in _init_compiled
    default:     for grp, m in enumerate(parameters)
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 692, in construct_params
    default:     pd[self.bind_names[bindparam]] = bindparam.effective_value
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 1213, in effective_value
    default:     return self.callable()
    default:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1587, in _go
    default:     % (column, state_str(state))
    default: sqlalchemy.exc.StatementError
    default: : (sqlalchemy.exc.InvalidRequestError) Can't resolve value for column configuration.id on object <Configuration at 0x7f8596b5ca10>; no value has been set for this column
    default: [SQL: SELECT count(*) AS count_1 
    default: FROM (SELECT result.id AS result_id, result.configuration_id AS result_configuration_id, result.machine_id AS result_machine_id, result.input_id AS result_input_id, result.tuning_run_id AS result_tuning_run_id, result.collection_date AS result_collection_date, result.collection_cost AS result_collection_cost, result.state AS result_state, result.time AS result_time, result.accuracy AS result_accuracy, result.energy AS result_energy, result.size AS result_size, result.confidence AS result_confidence, result.was_new_best AS result_was_new_best 
    default: FROM result 
    default: WHERE ? = result.tuning_run_id AND ? = result.configuration_id) AS anon_1]
    default: [parameters: [{}]]```

**Comment by ZiyingShao** [comment]
I had the same problem when I ran the code with SQLAlchemy version==1.3.3, the problem disappeared when I switched the version to 1.2.18.

**Comment by michael-hahn** [comment]
Yes. Once downgraded, it works fine. The issue was related to OpenTuner.
